"""connector_layer"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.String(length=200), server_default="__legacy__", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connector_credentials_owner_id"), "connector_credentials", ["owner_id"], unique=False)
    op.create_table(
        "connector_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("external_event_id", sa.String(length=300), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_event_id", name="uq_connector_event"),
    )
    op.create_table(
        "connector_oauth_states",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("verifier_encrypted", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.String(length=200), server_default="__legacy__", nullable=False),
        sa.PrimaryKeyConstraint("state_hash"),
    )
    op.create_index(op.f("ix_connector_oauth_states_owner_id"), "connector_oauth_states", ["owner_id"], unique=False)
    op.create_table(
        "connector_rate_limits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("next_allowed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "connector_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("transport_type", sa.String(length=30), server_default="direct", nullable=False),
        sa.Column("external_account_id", sa.String(length=300), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=40), server_default="connected", nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("credential_reference", sa.Uuid(), nullable=True),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("sync_cursor", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("sync_status", sa.String(length=40), server_default="idle", nullable=False),
        sa.Column("authentication_status", sa.String(length=30), server_default="valid", nullable=False),
        sa.Column("provider_health", sa.String(length=30), server_default="unknown", nullable=False),
        sa.Column("last_successful_request", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconcile_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("owner_id", sa.String(length=200), server_default="__legacy__", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("provider IN ('gmail','google_drive','github','slack')", name="ck_connector_provider"),
        sa.ForeignKeyConstraint(
            ["credential_reference"],
            ["connector_credentials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "provider", "external_account_id", name="uq_connector_account_identity"),
    )
    op.create_index(op.f("ix_connector_accounts_owner_id"), "connector_accounts", ["owner_id"], unique=False)
    op.create_index(op.f("ix_connector_accounts_reconcile_at"), "connector_accounts", ["reconcile_at"], unique=False)
    op.create_table(
        "connector_audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("owner_id", sa.String(length=200), server_default="__legacy__", nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["connector_accounts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connector_audit_owner_id"), "connector_audit", ["owner_id"], unique=False)
    op.create_table(
        "connector_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.String(length=500), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["connector_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_subscriptions_account_id"), "connector_subscriptions", ["account_id"], unique=False
    )
    op.create_table(
        "connector_sync_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), server_default="pending", nullable=False),
        sa.Column("cursor", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["connector_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connector_sync_jobs_account_id"), "connector_sync_jobs", ["account_id"], unique=False)
    op.create_index(op.f("ix_connector_sync_jobs_available_at"), "connector_sync_jobs", ["available_at"], unique=False)
    op.create_index(op.f("ix_connector_sync_jobs_status"), "connector_sync_jobs", ["status"], unique=False)
    op.create_table(
        "connector_resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_parent_id", sa.Text(), nullable=True),
        sa.Column("external_version", sa.String(length=300), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["connector_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "external_id", name="uq_connector_resource"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_index(op.f("ix_connector_resources_account_id"), "connector_resources", ["account_id"], unique=False)
    op.add_column("knowledge_sources", sa.Column("external_identity", sa.String(length=64), nullable=True))
    op.add_column("knowledge_sources", sa.Column("connector_account_id", sa.Uuid(), nullable=True))
    op.add_column("knowledge_sources", sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False))
    op.add_column("knowledge_sources", sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("uq_source_owner_hash"), "knowledge_sources", type_="unique")
    op.create_index(
        "uq_source_owner_hash",
        "knowledge_sources",
        ["owner_id", "file_hash"],
        unique=True,
        postgresql_where=sa.text("external_identity IS NULL"),
    )
    op.create_index(
        op.f("ix_knowledge_sources_connector_account_id"), "knowledge_sources", ["connector_account_id"], unique=False
    )
    op.create_index(
        "uq_source_external_identity",
        "knowledge_sources",
        ["owner_id", "external_identity"],
        unique=True,
        postgresql_where=sa.text("external_identity IS NOT NULL"),
    )
    op.create_foreign_key(
        "fk_source_connector", "knowledge_sources", "connector_accounts", ["connector_account_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if (
        op.get_bind()
        .execute(sa.text("SELECT 1 FROM knowledge_sources GROUP BY owner_id, file_hash HAVING count(*) > 1 LIMIT 1"))
        .scalar()
    ):
        raise RuntimeError("Downgrade would merge independent source identities; resolve duplicates explicitly first")
    op.drop_constraint("fk_source_connector", "knowledge_sources", type_="foreignkey")
    op.drop_index(
        "uq_source_external_identity",
        table_name="knowledge_sources",
        postgresql_where=sa.text("external_identity IS NOT NULL"),
    )
    op.drop_index(op.f("ix_knowledge_sources_connector_account_id"), table_name="knowledge_sources")
    op.drop_index(
        "uq_source_owner_hash", table_name="knowledge_sources", postgresql_where=sa.text("external_identity IS NULL")
    )
    op.create_unique_constraint(
        op.f("uq_source_owner_hash"),
        "knowledge_sources",
        ["owner_id", "file_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("knowledge_sources", "access_expires_at")
    op.drop_column("knowledge_sources", "is_active")
    op.drop_column("knowledge_sources", "connector_account_id")
    op.drop_column("knowledge_sources", "external_identity")
    op.drop_index(op.f("ix_connector_resources_account_id"), table_name="connector_resources")
    op.drop_table("connector_resources")
    op.drop_index(op.f("ix_connector_sync_jobs_status"), table_name="connector_sync_jobs")
    op.drop_index(op.f("ix_connector_sync_jobs_available_at"), table_name="connector_sync_jobs")
    op.drop_index(op.f("ix_connector_sync_jobs_account_id"), table_name="connector_sync_jobs")
    op.drop_table("connector_sync_jobs")
    op.drop_index(op.f("ix_connector_subscriptions_account_id"), table_name="connector_subscriptions")
    op.drop_table("connector_subscriptions")
    op.drop_index(op.f("ix_connector_audit_owner_id"), table_name="connector_audit")
    op.drop_table("connector_audit")
    op.drop_index(op.f("ix_connector_accounts_reconcile_at"), table_name="connector_accounts")
    op.drop_index(op.f("ix_connector_accounts_owner_id"), table_name="connector_accounts")
    op.drop_table("connector_accounts")
    op.drop_table("connector_rate_limits")
    op.drop_index(op.f("ix_connector_oauth_states_owner_id"), table_name="connector_oauth_states")
    op.drop_table("connector_oauth_states")
    op.drop_table("connector_events")
    op.drop_index(op.f("ix_connector_credentials_owner_id"), table_name="connector_credentials")
    op.drop_table("connector_credentials")
    # ### end Alembic commands ###
